import 'package:smart_wardrobe/features/wardrobe/data/models/clothing_item.dart';
import 'package:smart_wardrobe/features/wardrobe/data/repositories/wardrobe_repository.dart';

class SeedData {
  static Future<void> seedIfEmpty(WardrobeRepository repo) async {
    if (repo.getAllItems().isNotEmpty) return;

    final items = [
      ClothingItem(
        name: 'Classic White Tee',
        imagePath: '',
        category: 'Tops',
        color: 'White',
        brand: 'Uniqlo',
        season: 'All Season',
        pattern: 'Solid',
        occasion: 'Casual',
        colorHex: '#FFFFFF',
        wearCount: 12,
        lastWornDate: DateTime.now().subtract(const Duration(days: 2)),
      ),
      ClothingItem(
        name: 'Slim Black Jeans',
        imagePath: '',
        category: 'Bottoms',
        color: 'Black',
        brand: 'Levi\'s',
        season: 'All Season',
        pattern: 'Solid',
        occasion: 'Casual',
        colorHex: '#1A1A1A',
        wearCount: 18,
        lastWornDate: DateTime.now().subtract(const Duration(days: 1)),
      ),
      ClothingItem(
        name: 'Navy Oxford Shirt',
        imagePath: '',
        category: 'Tops',
        color: 'Navy',
        brand: 'Ralph Lauren',
        season: 'All Season',
        pattern: 'Solid',
        occasion: 'Work',
        colorHex: '#001F5B',
        wearCount: 6,
        lastWornDate: DateTime.now().subtract(const Duration(days: 7)),
      ),
      ClothingItem(
        name: 'Beige Chino Trousers',
        imagePath: '',
        category: 'Bottoms',
        color: 'Beige',
        brand: 'Zara',
        season: 'Spring',
        pattern: 'Solid',
        occasion: 'Work',
        colorHex: '#F5F5DC',
        wearCount: 5,
        lastWornDate: DateTime.now().subtract(const Duration(days: 14)),
      ),
      ClothingItem(
        name: 'White Sneakers',
        imagePath: '',
        category: 'Shoes',
        color: 'White',
        brand: 'Adidas',
        season: 'All Season',
        pattern: 'Solid',
        occasion: 'Casual',
        colorHex: '#FFFFFF',
        wearCount: 22,
        lastWornDate: DateTime.now().subtract(const Duration(days: 1)),
      ),
      ClothingItem(
        name: 'Floral Summer Dress',
        imagePath: '',
        category: 'Dresses',
        color: 'Multicolor',
        brand: 'H&M',
        season: 'Summer',
        pattern: 'Floral',
        occasion: 'Casual',
        colorHex: '#FF6B6B',
        wearCount: 2,
        lastWornDate: DateTime.now().subtract(const Duration(days: 95)),
      ),
      ClothingItem(
        name: 'Grey Knit Sweater',
        imagePath: '',
        category: 'Tops',
        color: 'Gray',
        brand: 'Cos',
        season: 'Winter',
        pattern: 'Solid',
        occasion: 'Casual',
        colorHex: '#808080',
        wearCount: 9,
        lastWornDate: DateTime.now().subtract(const Duration(days: 20)),
      ),
      ClothingItem(
        name: 'Black Watch',
        imagePath: '',
        category: 'Accessories',
        color: 'Black',
        brand: 'Casio',
        season: 'All Season',
        pattern: 'Solid',
        occasion: 'Casual',
        colorHex: '#1A1A1A',
        wearCount: 30,
        lastWornDate: DateTime.now(),
      ),
      ClothingItem(
        name: 'Denim Jacket',
        imagePath: '',
        category: 'Outerwear',
        color: 'Blue',
        brand: 'Levi\'s',
        season: 'Autumn',
        pattern: 'Solid',
        occasion: 'Casual',
        colorHex: '#2196F3',
        wearCount: 4,
        lastWornDate: DateTime.now().subtract(const Duration(days: 30)),
      ),
      ClothingItem(
        name: 'Running Shoes',
        imagePath: '',
        category: 'Shoes',
        color: 'Blue',
        brand: 'Nike',
        season: 'All Season',
        pattern: 'Solid',
        occasion: 'Sport',
        colorHex: '#2196F3',
        wearCount: 0,
        lastWornDate: null,
      ),
      ClothingItem(
        name: 'Silk Blouse',
        imagePath: '',
        category: 'Tops',
        color: 'Pink',
        brand: 'Massimo Dutti',
        season: 'Spring',
        pattern: 'Solid',
        occasion: 'Work',
        colorHex: '#E91E63',
        wearCount: 1,
        lastWornDate: DateTime.now().subtract(const Duration(days: 120)),
        isFavorite: true,
      ),
      ClothingItem(
        name: 'Sports Leggings',
        imagePath: '',
        category: 'Activewear',
        color: 'Black',
        brand: 'Lululemon',
        season: 'All Season',
        pattern: 'Solid',
        occasion: 'Sport',
        colorHex: '#1A1A1A',
        wearCount: 14,
        lastWornDate: DateTime.now().subtract(const Duration(days: 3)),
        isFavorite: true,
      ),
    ];

    for (final item in items) {
      await repo.addItem(item);
    }
  }
}
